language: node_js
node_js:
  - node
branches:
  only:
    - master
before_install:
  git clone https://github.com/aoh/radamsa.git && cd radamsa && make && sudo make install
script:
  npm install && npm test
